# Server
server:
  port: 8080
  tomcat:
    accept-count: 1000
  host: 127.0.0.1


config:
  mail:
    username: tnr-support@sphinxjsc.com
    pathDomain: https://tnre-admin-test.netlify.app/
    timeout: 30
  valid:
    time-minutes-valid: 5 # valid in 2 minutes
    otp-valid-seconds: 300

# Spring
spring:
  application:
    name: VSHIPPING-ADMIN
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
    enabled: false
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd/MM/yyyy HH:mm:ss
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://45.118.144.25:54320/QLVT_dev
    username: postgres
    password: NIW2023Aa@
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    datasource:
#      url: jdbc:postgresql://45.118.144.25:54320/QLVT_dev
#      username: postgres
#      password: NIW2023Aa@
#      hikari:
#        connection-timeout: 5000
#        maximum-pool-size: 20
#      jpa:
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        properties:
#          hibernate:
#            generate_statistics: false
#        hibernate:
#          ddl-auto: update
#        show-sql: false
  #send mail config
  mail:
    default-encoding: UTF-8
    default-website: https://tng-holdings.vn/
    host: smtp.office365.com
    port: 587
    username: tnr-support@sphinxjsc.com
    password: Sphinx@1234
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.office365.com
    test-connection: false
    list-receiver: LanLNT1@sphinxjsc.com, xuanduongtnteco@gmail.com, duyhoangdominic@gmail.com, AnDT@sphinxjsc.com, TuPA@sphinxjsc.com,minhnh@sphinxjsc.com, longnd@sphinxjsc.com,hieuvt@sphinxjsc.com,dongvd@sphinxjsc.com, tungnh@sphinxjsc.com, trungdq@sphinxjsc.com, duongtt@sphinxjsc.com, DungDV1@sphinxjsc.com, hungran.test@gmail.com
    send-only-sphinx: true

# Services
rest:
  connectTimeout: 30s
  readTimeout: 30s

security:
  basic:
    enable: false

  jwt:
    expiration: 1800000
    secret: JwtSecretKey
    jwtExpirationMs: 7200000

  server:
    error:
      include-message: ALWAYS
      include-stacktrace: never
